#!/bin/bash
# CLI ITK module location 
exeDir=/a/lfm23/Doutorado/Image-Registration/NormalizedAlgorithms/3DNormalizedMachadoMIOptimizer/debug
# Patient folders location
dataDir=

cd $dataDir
current=`echo $PWD`

metricTypeFolder="Tsallis"
#metricTypeFolder="TsallisNorm"
#metricTypeFolder="Mattes"

#i=0 # counter for found pair of images

#listing only folders
for folder in `ls -A1 *0*`; do
	
	# entering inside each image folder
	# Verifying if T1 and CT exists before calling the .exe CLI
	#if [ "$folder" = "$current/022/" ]; then
	cd $current/$folder
	if t1=`ls -c -ltd -- *T1*.nrrd`; then
		T1file=$current/$folder*T1*.nrrd
		if ct=`ls -c -ltd -- *CT*.nrrd`; then
			CTfile=$current/$folder*CT*.nrrd	# found T1 and CT file!
			
			echo "Patient $folder."

			# Calling CLI and sending CT and T1 from each folder;
			# We will consider CT as the fixed image and T1 as the moving one;
			
			# First we need to check if the metric type folder exists
			if test -f "$current/$folder/$metricTypeFolder" then
				cd $current/$folder/$metricTypeFolder
				$exeDir/MIRigidRegistration $CTfile $T1file $metricTypeFolder 1.50 -o -s  
			else
				mkdir $current/$folder/$metricTypeFolder
				cd $current/$folder/$metricTypeFolder
				$exeDir/MIRigidRegistration $CTfile $T1file $metricTypeFolder 1.50 -o -s
			fi
						
		else
			echo "CT file not found"
		fi	
	else
		echo "T1 file not found"
	fi
	#else
	#	echo "Not this one!"
	#fi

done
#echo $i